version: 0.0
os: linux
files:
  - source: core
    destination: /home/ec2-user/devops_project
hooks:
  BeforeInstall:
      - location: scripts/before_install.sh

  AfterInstall:
      - location: scripts/after_install.sh